*** [[https://www.youtube.com/watch?v=kT0HJkr1jj4][Science Proves There are More than Two Human Sexes]]

- title :: Science Proves There are More than Two Human Sexes
- group :: SciShow
- speaker :: Hank Green

"Nearly 2% of live births are born with congenital conditions of
atypical sex development."

**** Sources:
https://www.ncbi.nlm.nih.gov/pmc/arti...
http://www.isna.org/faq/what_is_intersex
https://www.hrw.org/report/2017/07/25...
https://www.scientificamerican.com/ar...
https://ghr.nlm.nih.gov/gene/SRY#cond...
https://www.who.int/genomics/gender/e...
https://www.wired.com/story/trumps-pl...
https://www.nature.com/news/sex-redef...
https://www.intersexequality.com/how-...
http://www.isna.org/faq/ten_myths/rare
https://onlinelibrary.wiley.com/doi/p...
https://my.clevelandclinic.org/health...
https://www.sciencedirect.com/science...
https://www.med.umich.edu/yourchild/t...
https://blogs.scientificamerican.com/...
http://blogs.discovermagazine.com/cru...
https://massivesci.com/articles/sex-g...
https://childrensnational.org/visit/c...
https://www.nationwidechildrens.org/s...
http://www.bloodjournal.org/content/1...
https://www.nytimes.com/2015/09/15/sc...
https://www.nadf.us/adrenal-diseases/...
https://www.nhs.uk/conditions/disorde...
http://aisdsd.org/resources/youth/you...
https://www.rchsd.org/programs-servic...
https://www.ncbi.nlm.nih.gov/pmc/arti...
https://www.seattlechildrens.org/clin...
https://www.fairview.org/patient-educ...
https://www.mayoclinic.org/diseases-c...
https://www.ncbi.nlm.nih.gov/pubmed/2...
https://www.ncbi.nlm.nih.gov/pubmed/2...

**** Image Sources

https://commons.wikimedia.org/wiki/Fi...
https://commons.wikimedia.org/wiki/Fi...
https://commons.wikimedia.org/wiki/Fi...
https://commons.wikimedia.org/wiki/Fi...
https://commons.wikimedia.org/wiki/Fi...

**** Additional Info

In this episode, we mentioned that those with XXX chromosomes sometimes have minor learning disorders, and that those with Turner syndrome may have mental disabilities. Everyone experiences these things differently, so these symptoms don't apply in all cases! But as for why they sometimes happen? Well, scientists aren't actually sure, and any ideas they do have are extremely complicated. Hopefully we'll know more soon!

**** Transcript

Intro

In high school biology, we usually learn that the sexes in humans are
fixed and concrete.  Whether you’re male or female is black-and-white
and rooted in your DNA: your 23rd pair of chromosomes is either two X
chromosomes or an X and a Y. That’s it. End of story.  And that’s
essentially what scientists thought, too. But it turns out that sex
isn’t that straightforward.

In fact, biologists today are saying sex is a spectrum.  And the
scientific community is still working on understanding and respecting
the people who fall in the middle of that spectrum.  Sex is a spectrum
To get this out of the way right up front: we’re not talking about
gender or sexuality here.

Gender refers to social and cultural attributes and understandings of
men and women and their roles—though, not every culture has only two
categories, and it’s increasingly seen as a spectrum.

Plus, the gender you identify as may or may not be the same one as what you express with
things like your clothing and behavior, all of which can also be on a spectrum.

Sexuality describes who you are attracted to, and it can be equally
complicated and on a spectrum. And where you are on these spectrums
isn’t necessarily fixed!

But what we are talking about today is your biology, including your
chromosomes, your hormones, your gonads, and your genitals.  The catch
is that these biological features don’t always agree with each other.
And they certainly don’t always conform to those high school health
class diagrams that tell us there is a single, universally correct
pathway to being male and female.

In fact, it’s estimated that nearly 2% of live births are born with
congenital conditions of atypical sex development. That basically
means that something in their chromosomes, hormones, gonads, or
genitals is different from what many people expect of a “boy” or a
“girl.”


This used to be known as being intersex, but these days, it’s better described as having

differences of sexual development, or DSDs.

And while nearly 2% might not sound like a lot, it means there could be 130 million people

or more with DSDs. If all those people were in one country, it'd be among the top ten

most populous countries in the world!

Plus, DSDs are not always something you can see. People can spend their whole lives thinking

they’re one sex based on anatomy only to find at least part of them tells a different story.
Sexual determination and sexual differentiation

You see, your sex is the result of both sexual determination and sexual differentiation.

Sexual determination has to do with what chromosomes you get. Those largely determine what happens

to your body during sexual differentiation—the process by which you develop the physiological

characteristics associated with your sex.

And contrary to what you might think, that differentiation doesn’t stop when you’re

born—it continues throughout your life.

That means there are a lot of moments where differences between people can happen—so

of course there are a ton of different outcomes!

We tend to put those outcomes into two boxes based on visible anatomy, or what scientists

call phenotypes. Phenotypical males have testicles and a penis, while phenotypical females have

ovaries, a uterus, a vagina, and vulva.

But in reality, none of the traits we use to discriminate between the sexes are truly

binary.

There’s a lot of variation within what we call male or female, and there's a lot of

overlap that's normal, too.

Anatomically, someone might look phenotypically female on the outside but not have ovaries

or a uterus, or have tissue from both ovaries and testes.

And genetics aren’t any clearer, because when it comes to chromosomes, people don’t

always get two Xs or an X and a Y.

Xs and Ys contain genes that help determine sex, with the Y chromosome conferring the

genes that enable you to develop male reproductive parts.

But the processes for producing sperm and eggs are really complicated, and they can

lead to lots of different results.

In this process, (abbreviated version) specialized cells basically duplicate themselves, then

undergo two rounds of division to produce reproductive cells, or gametes, that have

half of the parent’s genetic material. So, it makes one set of 23 chromosomes.

But sometimes, the chromosomes don’t split into exact sets of 23—and that means there

are a whole bunch of possible combinations of Xs and Ys that a person can end up with.

For instance, people can inherit three Xs or an X and two Ys. These folks are normally

taller than average.

Those with three Xs have slender builds, and sometimes have minor learning disorders. The

people who have an X and two YYs, on the other hand, tend to have more acne because of the

extra testosterone in their systems. In both cases, people retain full fertility.

Then, there’s Turner syndrome, which happens when you get just one X. That results in female

characteristics, but the people who have it tend to be shorter, don’t really go through

puberty, may have mental disabilities, and are sterile.

And Klinefelter syndrome, which results from two Xs and a Y, is the most common chromosomal

sex anomaly.

It happens in one in 600 male births and can cause lower testosterone production and cause

incomplete testicular development, though the symptoms can be minor enough that a person

isn’t diagnosed until later in life.

Now there’s also the fact that all your cells in your body don’t necessarily have

the same chromosomal makeup. Which like, what? Did I learn nothing but lies in high school?

But it’s true—someone with mosaicism can develop from a single fertilized egg, but

have a patchwork of genetically different cells.

And someone who’s a genetic chimera has different cells because they develop from

two different fertilized eggs that merge in the womb.

In both cases, it’s possible to end up with a mix of cells with different sex chromosomes.

And depending on the distribution of those cells, mosaicism and chimaerism can result

in ambiguous sexual characteristics or both male and female reproductive body parts.

It’s even been shown that pregnant people and their fetuses frequently swap stem cells

through the placenta in a phenomenon known as microchimerism. That means a chromosomal

“female” can be carrying around XY cells, and her son can have XX ones.
Sexdetermining genes

In some studies, these cells have been shown to stick around in the mother for several decades.

But all that said… there are also plenty of people with double-X or XY chromosomes

that also have differences of sexual development.

That’s in part because at least 25 genes play a role in sex differentiation. So both

mutations and relocations of these genes can result in a range of differences.

Genes necessary for male development can be swapped onto the X chromosome, for example,

or someone can end up with multiple or mutated versions of other sex-determining genes.

And some of these are on other chromosomes, and are inherited as run-of-the-mill recessive traits.

All of these genes really start to be influential around six weeks of development.

You see, at six weeks, the fetus has a pair of bulges called the gonadal ridges next to

its kidneys—and they have the potential to develop into ovaries or testes.

The fetus at this point also has two sets of ducts. One set can develop into the uterus

and fallopian tubes, while the other set has the potential to become the epididymis, vas

deferens, and seminal vesicles.

And what happens from there is somewhat of a balancing act of different genes working

in concert.

Essentially, different networks of genes shout MALE and FEMALE, and when that balance gets

knocked slightly askew, it can move a person along the sex spectrum.

Take SRY. Discovered in the 1990s, this is the male programming gene, and it has a big

effect on development.

If it ends up on the chromosome of someone who is XX, it can cause them to develop testes

instead of ovaries.

This can happen because there’s a step in sperm and egg production when chromosomes

swap some DNA with their partner chromosomes.

And even though the X and Y chromosomes generally don’t join in on this DNA swapping process,

they sometimes do.

Plus, other mutations that occur during the production of gametes can result in multiple

or mutated versions of SRY or other sex-determining genes—because it’s not

the only gene that matters.

There are also genes that actively encourage the fetus to develop female characteristics.

For instance, the gene WNT4 suppresses testicular development and promotes ovarian development,

and multiple copies of it can cause incomplete female gonads to develop in people who are XY.

Gonad development also triggers the production of sex-specific hormones, which results in

further sex-specific development.

But some people have differences of sex differentiation that limit their ability to respond to those hormones.

Complete androgen insensitivity syndrome is one of these. People who have it are unaffected

by male sex hormones, because they have some kind of mutation to the protein that these

hormones bind to, called the Androgen Receptor.

And that means that while they have testes and a Y chromosome, their exterior genitals

appear female or in between.

There’s also congenital adrenal hyperplasia, the most common DSD out there.

That’s when the adrenal glands underproduce cortisol and overproduce androgens, the male

hormone group that includes testosterone.

The underproduction of cortisol can lead to health problems, while the overproduction

of androgens can lead to external male genitalia paired with internal female gonads in people

with XX chromosomes.

Some of these conditions don’t fully present themselves until puberty or later.

In fact, some aren’t realized at all until a person seeks some kind of medical care that

reveals them. Like, in 2014, doctors reported one case of a 70-year-old father of 4 whose

quote “hernia” turned out to be a uterus with fallopian tubes.

But, in many cases, differences in sexual development are notable from birth; for those

newborns, it may be possible to assign a gender based on what they are more likely to identify

as, as they grow up.

The thing is, with all of the things that can happen during sexual development, when

a child is born with an obvious difference of sex development, it's not always clear why.

Looking at chromosomes often isn’t enough, and sometimes a hormonal test isn’t either.

And even if the child’s doctors have a sense of what’s going on, determining what, if

any, treatment is necessary can be challenging.

Back in the 1960s, it was thought that growing up without clearly defined sexual organs would

cause emotional trauma. So, there was a push towards performing surgery on infants to clearly

assign them a sex.

And because of social stigmas surrounding DSDs, parents were often encouraged to keep

all this a secret, even from the child. So people grew up without knowing kind of important

details about their own bodies.

It’s hard to get numbers on how many of these surgeries were—or even are being—performed.

It’s also hard to know exactly how these surgeries affect patients, but as adults,

many report pain, scarring, and a loss of sensation.

Also, people with DSDs do report high rates of gender dysphoria, where their chosen gender

does not align with their assigned sex.

And there is an association between gender dysphoria and mental health issues, like self-harm

behaviors, so these surgeries may contribute to mental health problems later in life.

Though, it’s important to note that such issues are less likely if people have supportive

and affirming parents who accept them as they are.

And, sometimes, surgery is medically necessary, like to unblock the urethra.

Also, surgery can help to preserve fertility or, in the case of complete androgen insensitivity

syndrome, to reduce the risk of testicular cancer.

But from a medical perspective, those surgeries don’t need to be performed on infants.

In fact, most of the time, differences in genital anatomy at birth aren’t something

that needs to be fixed. At least, not until the person is old enough to make their own

choices about what they want their bodies to look like.

So nowadays, healthcare is moving away from a surgical approach. If a DSD is identified

at birth, treatment is more likely to include therapy and hormonal replacement than surgery.

Often, a DSD team is involved in care, which can include geneticists, endocrinologists,

and psychologists or psychiatrists.

They help the family decide if any interventions are immediately and medically necessary, and

help provide care and support to the child with DSD and their family throughout childhood.

Unfortunately, this kind of care still isn’t available everywhere.

For now, researchers are working to better understand the development of both sex and

gender over time, and to gain a clearer sense of when kids begin to understand

their own gender identity.

The problem, of course, is the fact that from clothes to restrooms to organized sports,

they are raised in a society that is set up around a binary that just… isn’t binary.

But researchers are thinking about how we can make our overall discussions and understanding

of sex even more inclusive—and more accurate.

Because even though biological sex may seem like one of those things that is relatively

straightforward in a very, very complicated world… it’s not!

And while there’s probably still a long way to go to understand it,

we are making progress.

Before we go, we’d like to give a special thank you to our patrons on Patreon. It’s

because of their support that we’re able to tackle complex, difficult topics like this

one. So thank you, patrons! And if you want to support us, too, you can learn more

by joining our patron community at Patreon.com/SciShow

